import type { Metadata } from "next";
import "./globals.css";
import { cookies } from "next/headers";
import { Toaster } from "@/components/ui/sonner";
import { AuthErrorListener } from "@/components/auth/auth-error-listener";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Best-effort SSR theme class using cookie to minimize hydration mismatch.
  // Falls back to no class on first visit; client script will correct immediately.
  const cookieStore = await cookies();
  const themeCookie = cookieStore.get("theme")?.value; // ← ここは同じ
  const ssrHtmlClass = themeCookie === "dark" ? "dark" : undefined;
  return (
    <html lang="en" suppressHydrationWarning className={ssrHtmlClass}>
      <body className={`antialiased bg-[var(--background)] text-[var(--foreground)] transition-colors duration-300`}>
        {/* Theme no-flash init */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var m=document.cookie.match(/(?:^|; )theme=([^;]+)/);var cs=m?decodeURIComponent(m[1]):null;var ls=localStorage.getItem('theme');var v=cs||ls;var e=v?v==='dark':false;document.documentElement.classList.toggle('dark',e);}catch(e){}})();",
          }}
        />
        {children}
        <Toaster />
        <AuthErrorListener />
      </body>
    </html>
  );
}
