import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const noto_sans_jp = Noto_Sans_JP({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto_sans_jp.variable} antialiased bg-[var(--background)] text-[var(--foreground)] transition-colors duration-300`}>
        {/* Theme no-flash init */}
        <script
          dangerouslySetInnerHTML={{
            __html:
              "(function(){try{var s=localStorage.getItem('theme');var d=window.matchMedia('(prefers-color-scheme: dark)').matches;var e=s?s==='dark':d;var c=document.documentElement.classList;c.toggle('dark',e);}catch(e){}})();",
          }}
        />
        {/* Global Header */}
        <Header />
        <div className="pt-16 min-h-[calc(100dvh-6rem)]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
